### PR TITLE
Include examples with yarn monorepo

### PR DESCRIPTION
**Pull request by ofhouse**
Hey,

first I want to thank you for providing this plugin, it's really helpful and easy to use. 👍

I noticed that for development I currently need to checkout two repositories (this and https://github.com/titonobre/storybook-addon-angularjs-example) to have an example app and the plugin itself.
Since I am not a big fan of `npm link` I think it would be much easier for development purposes to bring both repos together in a monorepo.
Therefore I only need a single `yarn` and and the example is automatically linked to the plugin.

So I copied the example repo into a subfolder `example` with `git subtree` (the original commits from the example repo are preserved).

The only downside of it is, that you may not get more GitHub stars on the example repo because it's no longer needed but I think that's bearable.

### CODE REVIEW

**Comment by titonobre** [comment]
Hi.
Glad to know that this is helping you.

May I ask what is the motivation to need a link for the package? 

Merging this into a single repository was indeed part of my plans for the next steps. I've also struggled with `npm link` in the past but never considered to use Yarn Workspaces for this project. I will learn a bit more about this and get back to you.

About losing the GitHub stars, I think I can live with that. 😄

Side Note:
During the last few days I've been working on this project to make it even easier to use and to improve the examples. I will push my changes soon.

**Comment by ofhouse** [comment]
Oh yeah sorry I understand that the PR looks confusing because it does not add new content to the library itself. 😁

I also work on an extension of your plugin which brings support for mocking services (The hook solution is fine, but only supports the modification of services that already exist).

So the PR only contains the setup I've done before I started with the extension of the plugin.
Thought it would be better to submit it upfront so you can decide whether to adopt the new structure while I am working on the extension.

So whatever your decision on this is, I will modify my next PR to match the existing structure.

**Comment by titonobre** [comment]
Did you had any success with the the mocks?

I'm doing the final checks on my refactor which will be committed very soon. Keep an eye on the repository because the changes may ease your work with the mocks.

What I will do next?
1. finish my changes (lib+examples) and push the new branch
2. rebase my changes on top of your branch to test everything
3. merge your PR
4. merge my changes

I guess I messed up my repository while publishing version 0.1 at 3AM 🤦‍♂ It was supposed to be done from `master` branch and not from `register`. I fixed this with version 0.1.1 and I changed the target branch of your PR to master.

**Comment by ofhouse** [comment]
I already got a prototype for mocking services working here (needs some final touches and documentation): https://github.com/ofhouse/storybook-addon-angularjs/tree/ofhouse/mocks

The code for the mocks is not that much complicated so I think I will be able to adapt it to your changes once you pushed them.
The main idea is to create an another angular module and attach providers for the mocks to it.
Then I load the mock module before the original app module in the injector which makes all providers from the mock module available in the app module.

Yeah noticed that the `register` branch was more up-to-date but already thought that this was done by mistake.
Ok, so don't need to hurry, take your time and once you're finished I will come up with my PR for the mocks 👍

**Pull request merged**
